"""Two colours for every tab: light as written, dark from tools/theme-dark.json.

    python3 tools/theme-vars.py

In the tabs' CSS (the files below), each #hex inside a declaration becomes
var(--dbc-<role>-<hex>) - role fg for text, bg for backgrounds, bd for
borders, outlines and shadows. src/theme-table.js is rewritten with every
variable: in :root its light value is the hex itself, so light mode looks
exactly as the CSS was written; under html.db-dark it takes the dark value
from tools/theme-dark.json. Run again after writing new colours; a colour
with no dark value is listed and keeps its light one until it gets one.
SVG attributes (fill=, stroke=) are left alone, and so are rules that are
dark already (selector starting html.db-dark) - their colours are the dark
ones.
"""
import json
import re
import sys

FILES = [
    'src/code-view.js',
    'src/flow-editor.js',
    'src/features/form-logic.js',
    'src/features/form-dump.js',
    'src/features/form-commands.js',
    'src/features/workflow.js',
    'src/features/journey.js',
    'src/features/canvas-code.js',
    'src/features/flow-run-export.js',
    'src/features/env-compare.js',
    'src/help.js',
]

DECL = re.compile(r'([a-z-]+)(\s*:\s*)([^;{}\'"]*?#[0-9a-fA-F]{3,8}\b[^;{}\'"]*)')
HEX = re.compile(r'#([0-9a-fA-F]{3,8})\b')
VAR = re.compile(r'var\(--dbc-(fg|bg|bd)-([0-9a-f]{3,8})\)')
DARK_RULE = re.compile(r'html\.db-dark[^{}\'"]*\{[^{}]*\}')


def role(prop):
    if prop in ('color', 'caret-color', 'fill', 'stroke'):
        return 'fg'
    if prop.startswith('background'):
        return 'bg'
    return 'bd'


def convert(text, seen):
    def decl(m):
        r = role(m.group(1))

        def one(h):
            hx = h.group(1).lower()
            seen.add((r, hx))
            return 'var(--dbc-%s-%s)' % (r, hx)

        return m.group(1) + m.group(2) + HEX.sub(one, m.group(3))

    parts, at = [], 0
    for m in DARK_RULE.finditer(text):
        parts.append(DECL.sub(decl, text[at:m.start()]))
        parts.append(m.group(0))
        at = m.end()
    parts.append(DECL.sub(decl, text[at:]))
    out = ''.join(parts)
    for r, hx in VAR.findall(out):
        seen.add((r, hx))
    return out


def main():
    dark = json.load(open('tools/theme-dark.json'))
    seen = set()
    for f in FILES:
        src = open(f, encoding='utf-8').read()
        new = convert(src, seen)
        if new != src:
            open(f, 'w', encoding='utf-8').write(new)
    missing = sorted(k for k in seen if k[1] not in dark.get(k[0], {}))
    light = ''.join('--dbc-%s-%s:#%s;' % (r, h, h) for r, h in sorted(seen))
    night = ''.join('--dbc-%s-%s:%s;' % (r, h, dark[r].get(h, '#' + h)) for r, h in sorted(seen))
    open('src/theme-table.js', 'w', encoding='utf-8').write(
        '/* DynaBoost - the tabs\' colours in light and dark. Generated by\n'
        ' * tools/theme-vars.py from the tabs\' CSS and tools/theme-dark.json -\n'
        ' * edit those, then run it; do not edit this file. */\n'
        '(function () {\n'
        '  window.DynaBoost = window.DynaBoost || {};\n'
        "  DynaBoost.themeVars =\n    ':root{" + light + "}' +\n"
        "    'html.db-dark{color-scheme:dark;" + night + "}';\n"
        '})();\n'
    )
    print('%d colours in use' % len(seen))
    if missing:
        print('no dark value yet (kept light):', ', '.join('%s #%s' % k for k in missing))
        sys.exit(1)


main()
